name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # todos os dias às 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: reinaldobarreto
          outputs: |
            dist/snake.svg?color_snake=%2300E5FF&color_dots=%230D1117,%2300B8D4,%2300E5FF,%2302569B,%23FFC107
            dist/snake-light.svg?color_snake=%23FFC107&color_dots=%23B2EBF2,%2380DEEA,%2300E5FF,%2302569B,%23FFC107

      - name: Deploy SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: output
          build_dir: dist