name: Generate Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # todos os dias às 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/snake.yml
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: reinaldobarreto
          outputs: |
            dist/snake.svg?palette=github-dark&color_snake=%234C8CCB&color_dots=%230D1117,%23112B45,%23244B73,%2395C11F,%23FFD343
            dist/snake-light.svg?palette=github-light&color_snake=%233776AB&color_dots=%23F8FBFF,%23D8E6F5,%23A7C4E5,%23CFE28D,%23FFD343

      - name: Deploy SVG to output branch
        uses: crazy-max/ghaction-github-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: ${{ github.repository }}
          target_branch: output
          build_dir: dist
